#logging:
#  level:
#    org:
#      springframework: debug

server:
  port: 8081

#spring:
#  security:
#    user:
#      name: Rudraksh
#      password: dummy

jwt:
  get:
    token:
      uri: /authenticate